### PR TITLE
Update for compatibility with flask v2.3.2

### LINKED ISSUE #151: Tests broken with flask-2.3.2
After upgrading Flask to 2.3.2, the tests fail to collect:

```pytb
========================================================= test session starts =========================================================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: /tmp/flask-api
collected 6 items / 6 errors                                                                                                          

=============================================================== ERRORS ================================================================
____________________________________________ ERROR collecting flask_api/tests/test_app.py _____________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_exceptions.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_exceptions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_mediatypes.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_mediatypes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
________________________________________ ERROR collecting flask_api/tests/test_negotiation.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_negotiation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
__________________________________________ ERROR collecting flask_api/tests/test_parsers.py ___________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_parsers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_renderers.py __________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_renderers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
========================================================== warnings summary ===========================================================
flask_api/renderers.py:6
  /tmp/flask-api/flask_api/renderers.py:6: DeprecationWarning: '_request_ctx_stack' is deprecated and will be removed in Flask 2.4.
    from flask.globals import _request_ctx_stack

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= short test summary info =======================================================
ERROR flask_api/tests/test_app.py
ERROR flask_api/tests/test_exceptions.py
ERROR flask_api/tests/test_mediatypes.py
ERROR flask_api/tests/test_negotiation.py
ERROR flask_api/tests/test_parsers.py
ERROR flask_api/tests/test_renderers.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================== 1 warning, 6 errors in 0.77s =====================================================
```

### PR DESCRIPTION
**Pull request by dsakagi**
In version 2.3.0 of flask, the JSONEncoder class was removed and the app.json_encoder attribute was [removed](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0). The result that a run of the tests using flask==2.3.0 would fail. This change updates the use of flask's json mechanisms to be in line with the new standard, and similarly updates the tests to utilize those mechanisms correctly.

From other pull requests I wasn't able to tell whether there is still a Travis project that is watching this repository, but if there is and if I've understood the setup correctly, the tests should validate that this change causes the tests to pass with flask 2.3.2

Closes #151

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
@jacebrowning can we get a new release?

**Comment by jacebrowning** [comment]
https://github.com/flask-api/flask-api/pull/155

**Comment by auvipy** [comment]
thanks a lot. I will follow that
