### ISSUE TITLE
Tests broken with flask-2.3.2

### ISSUE THREAD

**Issue by mgorny** [flask-api/flask-api#151]
After upgrading Flask to 2.3.2, the tests fail to collect:

```pytb
========================================================= test session starts =========================================================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: /tmp/flask-api
collected 6 items / 6 errors                                                                                                          

=============================================================== ERRORS ================================================================
____________________________________________ ERROR collecting flask_api/tests/test_app.py _____________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_exceptions.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_exceptions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_mediatypes.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_mediatypes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
________________________________________ ERROR collecting flask_api/tests/test_negotiation.py _________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_negotiation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
__________________________________________ ERROR collecting flask_api/tests/test_parsers.py ___________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_parsers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
_________________________________________ ERROR collecting flask_api/tests/test_renderers.py __________________________________________
ImportError while importing test module '/tmp/flask-api/flask_api/tests/test_renderers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flask_api/tests/__init__.py:14: in <module>
    exec("from flask_api.tests.%s import *" % module)
flask_api/tests/test_renderers.py:4: in <module>
    from flask.json import JSONEncoder
E   ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/tmp/flask-api/.venv/lib/python3.11/site-packages/flask/json/__init__.py)
========================================================== warnings summary ===========================================================
flask_api/renderers.py:6
  /tmp/flask-api/flask_api/renderers.py:6: DeprecationWarning: '_request_ctx_stack' is deprecated and will be removed in Flask 2.4.
    from flask.globals import _request_ctx_stack

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= short test summary info =======================================================
ERROR flask_api/tests/test_app.py
ERROR flask_api/tests/test_exceptions.py
ERROR flask_api/tests/test_mediatypes.py
ERROR flask_api/tests/test_negotiation.py
ERROR flask_api/tests/test_parsers.py
ERROR flask_api/tests/test_renderers.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================== 1 warning, 6 errors in 0.77s =====================================================
```

**Comment by auvipy** [comment]
thanks for the report. you can contribute the fix. if you can't I will fix it

**Comment by mgorny** [comment]
I'm afraid I'm swamped with work right now.

**Comment by auvipy** [comment]
thanks! I will try to fix it this week

**Comment by mgorny** [comment]
Gentle ping. I've tried to look a quick look but I really have no clue about Flask and the deprecation note doesn't seem to provide a hint at a 1:1 solution for someone clueless.

**Comment by mgorny** [comment]
As a matter of explanation, I'm not using flask-api myself, I've merely ended up maintaining the Gentoo package for it. This package happens to be the only thing blocking Gentoo from upgrading to Flask 2.3, and since it doesn't seem to be needed by anything else in Gentoo I'm weighing whether we should wait for a fixed version or remove it entirely.

**Comment by mgorny** [comment]
Thank you!
